server.port: 8080

application:
  name: envoy-control

envoy-control:
  source:
    consul:
      host: localhost
  envoy:
    snapshot:
      incoming-permissions:
        enabled: true

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  metrics.export.prometheus.enabled: true
